### ISSUE TITLE
C4 plant diagrams is not working

### ISSUE THREAD

**Issue by Volland** [agirorn/metalsmith-plantuml#10]
Fail to render
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person_Ext(issuer, "Issuer")
Boundary(b1,"Verification") {
Person(holder, "Holder", $sprite="person2")
Person(verifier, "Verifier")
}

Rel_L(issuer, holder, "issue VC", "Request for offer")
Rel(holder, issuer, "claim", "Response for offer")
Rel_R(verifier, holder, "ask for VCs", "Request for sharing")
Rel(holder, verifier, "issue signed VP", "VP", $sprite = "&envelope-closed")

@enduml

**Comment by agirorn** [comment]
Thanks for the feedback. This should now be fixed in version 0.0.5

**Comment by Volland** [comment]
thanks. it makes my life a bit better!
